// Generated by @gamesome/route-builder
// Do not edit this file manually

import type { ExpandDeep } from '@gamesome/route-builder/generator';

type RawAppRoutes = {
	$: '/';
	dashboard: {
		$: '/dashboard';
		settings: '/dashboard/settings';
	};
	users: {
		$: '/users';
		id: (userId: string) => `/users/${string}`;
		profile: (userId: string) => {
			$: `/users/${string}/profile`;
			edit: {
				$: `/users/${string}/profile/edit`;
			};
		};
	};
	api: {
		$: '/api';
		v1: {
			$: '/api/v1';
			health: '/api/v1/health';
		};
	};
};

export type AppRoutes = ExpandDeep<RawAppRoutes>;
